name = "feature-runway"
compatibility_date = "2025-08-13"
pages_build_output_dir = "."

[durable_objects]
bindings = [
  # NOTE: script_name points at the Worker you deployed in Step 1.
  { name = "PAGE_DATA", class_name = "PageDataDO", script_name = "page-data-do" }
]
