
name = "feature-runway"
compatibility_date = "2025-08-13"
pages_build_output_dir = "."


[durable_objects]
bindings = [
	{ name = "PAGE_DATA", class_name = "PageDataDO", script_name = "feature-runway" }
]

